version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:latest

jobs:
  check:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build C++ 
          command: npm run build
      - run:
          name: Test 
          command: npm run test

workflows:
  version: 2
  build_and_test:
    jobs:
      - check
